services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --preload --workers 1 main:app
    envVars:
      - key: PORT
        value: 8080
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: LINEAR_API_KEY
        sync: false
      - key: GOOGLE_TOKEN_JSON
        sync: false
      - key: GOOGLE_CALENDAR_CREDENTIALS
        sync: false
      - key: TZ
        value: Europe/Prague
